### ISSUE TITLE
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'

### ISSUE THREAD

**Issue by rpp5524** [davidnvq/grit#57]
/usr/local/lib/python3.10/dist-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Traceback (most recent call last):
  File "/content/grit/train_caption.py", line 12, in <module>
    from models.caption.detector import build_detector
  File "/content/grit/models/caption/detector.py", line 8, in <module>
    from models.detection.det_module import build_det_module_with_config
  File "/content/grit/models/detection/det_module.py", line 19, in <module>
    from models.ops.modules import MSDeformAttn
  File "/content/grit/models/ops/modules/__init__.py", line 9, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "/content/grit/models/ops/modules/ms_deform_attn.py", line 13, in <module>
    from ..functions import MSDeformAttnFunction
  File "/content/grit/models/ops/functions/__init__.py", line 9, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "/content/grit/models/ops/functions/ms_deform_attn_func.py", line 18, in <module>
    import MultiScaleDeformableAttention as MSDA
ModuleNotFoundError: No module named 'MultiScaleDeformableAttention'

How do I resolve this error?

Also. This is how my directory structure looks like:
![image](https://github.com/user-attachments/assets/09a596a4-0a0c-469f-a246-4b4927641ce6)

**Comment by quangvnai** [comment]
Hi there, I am sorry for the late response. Have you figured out the solution?
It seems that you haven't installed Deformable Attention:
```cd models/ops/
python setup.py build develop
python test.py
```
